### PR TITLE
get_arp_table() using API

### PR DESCRIPTION
**Pull request by luqasz**

### CODE REVIEW

**Comment by luqasz** [comment]
```
test/unit/test_getters.py::TestGetter::test_get_arp_table[normal] <- ../../.virtualenvs/napalm-ros/lib/python2.7/site-packages/napalm_base/test/getters.py PASSED
```
On my machine.

**Comment by mirceaulinic** [comment]
... the famous "it works on my machine" :)

There were some changes in napalm-base 0.19.0, see https://github.com/napalm-automation/napalm-base/releases/tag/0.19.0

Don't be afraid, you will only need to rename mock files, as they can only contain a-z, A-Z and 0-9. Basically you'll need to do something similar to: https://github.com/napalm-automation/napalm-eos/pull/86

**Comment by dbarrosop** [comment]
Would you also mind deleting the old test for the migrated method? That will hopefully make the test go green once all the tests have been migrated.

**Comment by luqasz** [comment]
It fails because it searches for files in wrong path `/home/travis/build/napalm-automation/napalm-ros/test/api/mocked_data/test_get_facts/normal/_system_resource_print.json`
It should look in `/home/travis/build/napalm-automation/napalm-ros/test/unit/mocked_data/test_get_facts/normal/` so **unit** not **api**

**Comment by luqasz** [comment]
@mirceaulinic mocked data file is already named `_ip_arp_print.json`

**Pull request merged**
