### PR TITLE
get_interfaces() using API

### PR DESCRIPTION
**Pull request by luqasz**

### CODE REVIEW

**Comment by dbarrosop** [comment]
I just realized that the files required for the tsting are on the wrong folder. The files you have under `test/api` should be in `test/unit`. Either that or you move the mocked data but the framework expects both to be under the same tree. I think that's the same error you have on the other PR.

**Comment by luqasz** [comment]
When I did that I have lots of:
```
test/unit/conftest.py:33: in pytest_generate_tests
    parent_conftest.pytest_generate_tests(metafunc, __file__)
../../.virtualenvs/napalm-ros/lib/python2.7/site-packages/napalm_base/test/conftest.py:49: in pytest_generate_tests
    metafunc.parametrize("test_case", test_cases)
../../.virtualenvs/napalm-ros/lib/python2.7/site-packages/_pytest/python.py:823: in parametrize
    self.function, name, arg))
E   ValueError: <function test_password_encoding at 0x107d122a8> uses no argument u'test_case'
```

**Comment by dbarrosop** [comment]
Ok, let me try to fix it

**Comment by dbarrosop** [comment]
Ok, both PRs are fixed on #29. The problem wasn't dramatic at all, `napalm-base` was pinned to an older version, that was it.

**Comment by luqasz** [comment]
Thx.

**Pull request merged**
